"""Add modifiers to character

Revision ID: 7b9171c03cca
Revises: 
Create Date: 2025-01-08 00:41:15.175717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9171c03cca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength_modifier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dexterity_modifier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('constitution_modifier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intelligence_modifier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wisdom_modifier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('charisma_modifier', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('character_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strength',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dexterity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('constitution',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('intelligence',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wisdom',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('charisma',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('charisma',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wisdom',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('intelligence',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('constitution',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('dexterity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('strength',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('character_class',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('charisma_modifier')
        batch_op.drop_column('wisdom_modifier')
        batch_op.drop_column('intelligence_modifier')
        batch_op.drop_column('constitution_modifier')
        batch_op.drop_column('dexterity_modifier')
        batch_op.drop_column('strength_modifier')

    # ### end Alembic commands ###
